/**
 * Pictionary-style word lists: drawable only. No repeats in same room/session.
 * Easy = simple objects/animals/actions. Medium = concrete. Hard = longer but drawable.
 */

export const WORDS = {
  easy: [
    'cat', 'dog', 'sun', 'moon', 'star', 'fish', 'bird', 'ball', 'house', 'tree',
    'car', 'hat', 'book', 'cup', 'bed', 'apple', 'banana', 'flower', 'heart',
    'smile', 'rain', 'snow', 'fire', 'key', 'door', 'hand', 'foot', 'eye', 'nose',
    'run', 'jump', 'sit', 'sleep', 'eat', 'drink', 'swim', 'fly', 'walk', 'dance',
    'boat', 'bus', 'bike', 'cake', 'pizza', 'ice', 'wind', 'cloud', 'bee', 'bug',
    'frog', 'bear', 'lion', 'duck', 'pig', 'cow', 'horse', 'mouse', 'rabbit', 'bat',
    'pen', 'box', 'bag', 'bell', 'ring', 'lamp', 'fork', 'spoon', 'chair', 'table',
    'red', 'blue', 'green', 'yellow', 'wave', 'mountain', 'egg', 'leaf', 'stick',
    'ant', 'owl', 'fox', 'deer', 'wolf', 'seal', 'whale', 'shark', 'snake', 'turtle',
    'bee', 'spider', 'crab', 'clam', 'cloud', 'rainbow',
    'bread', 'milk', 'egg', 'cheese', 'rice', 'corn', 'grape', 'melon', 'peach',
    'pear', 'cherry', 'strawberry', 'orange', 'lemon', 'lime', 'carrot', 'potato',
    'tomato', 'onion', 'pepper', 'salad', 'soup', 'tea', 'coffee', 'juice', 'water',
    'king', 'queen', 'baby', 'angel', 'clown', 'robot', 'alien', 'monster', 'ghost',
    'bone', 'skull', 'crown', 'ring', 'gem', 'coin', 'flag', 'map', 'globe', 'anchor',
    'sword', 'shield', 'arrow', 'bow', 'castle', 'tower', 'bridge', 'fence', 'gate',
    'road', 'path', 'hill', 'river', 'lake', 'pond', 'ocean', 'island', 'cave',
    'tent', 'roof', 'window', 'stairs', 'ladder', 'hammer', 'nail', 'saw', 'rope',
    'brush', 'paint', 'pencil', 'paper', 'scissors', 'glue', 'tape', 'pin', 'needle',
    'thread', 'button', 'zipper', 'belt', 'shoe', 'sock', 'glove', 'scarf', 'umbrella',
    'watch', 'clock', 'phone', 'radio', 'camera', 'light', 'candle', 'mirror',
    'soap', 'towel', 'comb', 'toothbrush', 'pillow', 'blanket', 'broom', 'mop',
    'vase', 'bottle', 'jar', 'can', 'bucket', 'basket', 'net', 'hook', 'worm',
    'nest', 'feather', 'wing', 'tail', 'horn', 'hoof', 'paw', 'claw', 'beak',
    'trunk', 'tusk', 'fin', 'scale', 'shell', 'fur', 'stripes', 'spots',
    'kick', 'throw', 'catch', 'push', 'pull', 'climb', 'slide', 'roll', 'spin',
    'read', 'write', 'draw', 'sing', 'drum', 'whistle', 'blow', 'point', 'wave',
    'open', 'close', 'lock', 'knock', 'ring', 'wipe', 'sweep', 'stir',
    'pour', 'mix', 'cut', 'peel', 'slice', 'spread', 'fold', 'wrap', 'tie',
    'smell', 'taste', 'hear', 'see', 'touch', 'think', 'dream', 'wake', 'yawn',
    'sneeze', 'cough', 'laugh', 'cry', 'shout', 'whisper', 'hug', 'kiss', 'wave',
    'stomp', 'march', 'tiptoe', 'squat', 'bend', 'stretch', 'twist', 'shake',
    'camp', 'hike', 'fish', 'hunt', 'garden', 'cook', 'bake', 'grill', 'picnic',
    'party', 'birthday', 'present', 'balloon', 'confetti', 'cake', 'candle', 'wish',
    'snowman', 'snowball', 'sled', 'skate', 'ski', 'surf', 'dive', 'float', 'sail',
    'paddle', 'row', 'climb', 'zip', 'slide', 'swing', 'bounce', 'hop', 'skip',
  ],
  medium: [
    'elephant', 'giraffe', 'penguin', 'dolphin', 'butterfly', 'kangaroo', 'octopus',
    'umbrella', 'guitar', 'camera', 'bicycle', 'airplane', 'rocket', 'balloon',
    'birthday', 'castle', 'beach', 'mountain', 'campfire', 'telescope', 'treasure',
    'hamburger', 'sandwich', 'popcorn', 'watermelon', 'pineapple', 'coconut',
    'dancing', 'swimming', 'cooking', 'painting', 'fishing', 'camping', 'skating',
    'robot', 'pirate', 'crown', 'crystal', 'dragon', 'unicorn', 'mermaid', 'wizard',
    'rainbow', 'volcano', 'waterfall', 'lighthouse', 'windmill', 'tent', 'bridge',
    'snowman', 'scarecrow', 'skeleton', 'ghost', 'pumpkin', 'present', 'candle',
    'glasses', 'watch', 'backpack', 'kite', 'yo-yo', 'drum', 'violin', 'microphone',
    'surfing', 'skiing', 'soccer', 'basketball', 'bowling', 'frisbee', 'rollerblade',
    'peacock', 'flamingo', 'parrot', 'eagle', 'hawk', 'owl', 'pelican', 'stork',
    'swan', 'goose', 'turkey', 'chicken', 'rooster', 'pigeon', 'crow', 'sparrow',
    'crocodile', 'alligator', 'lizard', 'iguana', 'chameleon', 'gecko', 'salamander',
    'jellyfish', 'seahorse', 'starfish', 'octopus', 'squid', 'lobster', 'shrimp',
    'caterpillar', 'ladybug', 'dragonfly', 'firefly', 'grasshopper', 'cricket',
    'mosquito', 'beetle', 'snail', 'worm', 'ant', 'spider', 'scorpion', 'centipede',
    'tractor', 'helicopter', 'submarine', 'sailboat', 'canoe', 'kayak', 'surfboard',
    'skateboard', 'scooter', 'roller skates', 'sled', 'snowboard', 'skis', 'poles',
    'telescope', 'binoculars', 'compass', 'flashlight', 'lantern', 'magnifying glass',
    'backpack', 'suitcase', 'purse', 'wallet', 'keychain', 'lunchbox', 'thermos',
    'toothbrush', 'soap', 'shampoo', 'towel', 'sponge', 'mirror', 'hairbrush',
    'necklace', 'bracelet', 'earrings', 'ring', 'tiara', 'crown', 'mask', 'wig',
    'apron', 'oven mitt', 'pot', 'pan', 'spatula', 'ladle', 'colander', 'blender',
    'toaster', 'microwave', 'refrigerator', 'sink', 'faucet', 'dish', 'glass',
    'napkin', 'placemat', 'tablecloth', 'chopsticks', 'teapot', 'mug', 'pitcher',
    'hammock', 'swing set', 'sandbox', 'slide', 'seesaw', 'merry-go-round',
    'fountain', 'statue', 'bench', 'gazebo', 'fence', 'gate', 'mailbox', 'lawn',
    'garden', 'flower bed', 'vegetable', 'watering can', 'wheelbarrow', 'rake',
    'shovel', 'hoe', 'seeds', 'sprout', 'vine', 'bush', 'hedge', 'tree stump',
    'camping', 'bonfire', 'marshmallow', 'sleeping bag', 'campfire', 'flashlight',
    'fishing rod', 'bait', 'tackle box', 'life jacket', 'oar', 'anchor', 'buoy',
    'lifeguard', 'sunscreen', 'beach ball', 'sand castle', 'seashell', 'coral',
    'surfboard', 'wetsuit', 'snorkel', 'flippers', 'diving board', 'pool',
    'basketball hoop', 'tennis racket', 'golf club', 'baseball bat', 'helmet',
    'trophy', 'medal', 'podium', 'finish line', 'stopwatch', 'whistle', 'conductor',
    'microphone', 'speaker', 'stage', 'curtain', 'spotlight', 'costume', 'mask',
    'puppet', 'marionette', 'juggling', 'acrobat', 'magician', 'clown', 'mime',
    'artist', 'easel', 'palette', 'paintbrush', 'canvas', 'clay', 'sculpture',
    'mosaic', 'collage', 'sketch', 'portrait', 'landscape', 'still life',
    'superhero', 'cape', 'mask', 'shield', 'sword', 'wand', 'spell', 'cauldron',
    'treasure chest', 'gold coins', 'gem', 'crown', 'throne', 'dungeon', 'tower',
    'drawbridge', 'moat', 'knight', 'armor', 'helmet', 'horse', 'jousting',
    'spaceship', 'astronaut', 'planet', 'alien', 'robot', 'laser', 'satellite',
    'moon landing', 'rocket launch', 'constellation', 'comet', 'meteor', 'orbit',
    'hospital', 'stethoscope', 'bandage', 'syringe', 'pill', 'thermometer',
    'ambulance', 'wheelchair', 'crutches', 'cast', 'x-ray', 'doctor', 'nurse',
    'school', 'blackboard', 'desk', 'backpack', 'pencil case', 'ruler', 'eraser',
    'notebook', 'textbook', 'locker', 'recess', 'playground', 'cafeteria',
    'library', 'bookshelf', 'ladder', 'card catalog', 'reading', 'bookmark',
    'office', 'computer', 'keyboard', 'mouse', 'desk lamp', 'stapler', 'folder',
    'briefcase', 'name tag', 'coffee cup', 'plant', 'calendar', 'whiteboard',
    'bakery', 'donut', 'croissant', 'bagel', 'muffin', 'cookie', 'cupcake',
    'ice cream', 'cone', 'sundae', 'popsicle', 'smoothie', 'milkshake',
    'restaurant', 'menu', 'waiter', 'chef', 'kitchen', 'stove', 'grill',
    'grocery', 'shopping cart', 'checkout', 'cash register', 'shopping bag',
    'zoo', 'cage', 'safari', 'elephant', 'zebra', 'monkey', 'gorilla', 'lion',
    'aquarium', 'tank', 'coral', 'bubble', 'diver', 'fish food', 'net',
    'museum', 'painting', 'statue', 'exhibit', 'tour', 'guide', 'gift shop',
    'circus', 'tent', 'acrobat', 'trapeze', 'tightrope', 'lion tamer', 'ringmaster',
    'carnival', 'ferris wheel', 'carousel', 'bumper cars', 'cotton candy', 'funnel cake',
    'birthday party', 'pinata', 'balloons', 'streamers', 'party hat', 'noisemaker',
    'wedding', 'cake', 'bouquet', 'ring', 'veil', 'gown', 'tuxedo', 'altar',
    'halloween', 'costume', 'trick or treat', 'candy', 'jack-o-lantern', 'witch',
    'christmas', 'tree', 'ornament', 'lights', 'stocking', 'santa', 'reindeer',
    'snowflake', 'snowball', 'igloo', 'snow fort', 'snow angel', 'frost',
    'spring', 'bloom', 'butterfly', 'bee', 'nest', 'tulip', 'daffodil', 'cherry blossom',
    'summer', 'sun', 'beach', 'sunscreen', 'lemonade', 'ice cream', 'pool',
    'fall', 'leaves', 'harvest', 'pumpkin', 'apple', 'corn', 'scarecrow',
    'weather', 'rain', 'snow', 'wind', 'storm', 'lightning', 'thunder', 'rainbow',
  ],
  hard: [
    'birthday cake', 'roller coaster', 'hot air balloon', 'snowboarding', 'scuba diving',
    'rock concert', 'supermarket', 'traffic light', 'washing machine', 'toothbrush',
    'camping trip', 'treasure hunt', 'sand castle', 'snowball fight', 'water park',
    'movie theater', 'amusement park', 'sleeping bag', 'flying kite', 'building blocks',
    'pizza delivery', 'ice cream truck', 'fireworks', 'double decker bus',
    'skateboard', 'trampoline', 'merry-go-round', 'ferris wheel', 'lemonade stand',
    'picnic basket', 'fishing rod', 'baseball bat', 'barbecue', 'garden hose',
    'snow angel', 'smoothie', 'pancakes', 'breakfast', 'lunch box',
    'teddy bear', 'puzzle', 'snowflake', 'sunflower', 'cactus', 'palm tree',
    'ladybug', 'caterpillar', 'jellyfish', 'seahorse', 'starfish',
    'flashlight', 'binoculars', 'compass', 'campfire', 'marshmallow', 'kayak', 'parachute',
    'sleeping bag', 'tent', 'camping', 'hiking', 'fishing', 'kayak',
    'road trip', 'map reading', 'camping stove', 'first aid kit', 'headlamp',
    'sandwich', 'fruit salad', 'trail mix', 'energy bar', 'water bottle',
    'mountain climbing', 'rock climbing', 'zip line', 'rope bridge', 'cave exploring',
    'underwater', 'snorkeling', 'scuba tank', 'coral reef', 'shipwreck',
    'snow fort', 'snowball', 'sledding', 'ice skating', 'hockey', 'curling',
    'ski lift', 'snow plow', 'snow shovel', 'snow blower', 'fireplace',
    'roasting marshmallows', 'telling stories', 'singing songs', 'playing guitar',
    'building a fort', 'pillow fight', 'board game', 'card game', 'puzzle',
    'science experiment', 'volcano', 'tornado', 'solar system', 'microscope',
    'telescope', 'constellation', 'shooting star', 'eclipse', 'aurora',
    'rainbow', 'double rainbow', 'clouds', 'storm cloud', 'lightning bolt',
    'thunder', 'rain', 'drizzle', 'hail', 'sleet', 'blizzard', 'fog',
    'water cycle', 'evaporation', 'condensation', 'precipitation',
    'garden', 'vegetable garden', 'flower garden', 'greenhouse', 'compost',
    'watering plants', 'pruning', 'harvesting', 'canning', 'pickling',
    'baking cookies', 'making pizza', 'stir fry', 'soup', 'salad', 'smoothie',
    'birthday party', 'blowing candles', 'opening presents', 'pinata',
    'wedding', 'bride', 'groom', 'bouquet', 'first dance', 'cake cutting',
    'graduation', 'cap', 'gown', 'diploma', 'throw cap', 'celebration',
    'halloween', 'trick or treat', 'costume', 'candy', 'jack o lantern',
    'thanksgiving', 'turkey', 'feast', 'family', 'gratitude', 'harvest',
    'christmas', 'decorating tree', 'wrapping presents', 'caroling',
    'new year', 'countdown', 'fireworks', 'champagne', 'resolution',
    'easter', 'egg hunt', 'basket', 'bunny', 'chocolate', 'spring',
    'valentine', 'heart', 'cupid', 'chocolate', 'rose', 'love letter',
    'super bowl', 'football', 'tailgate', 'commercial', 'halftime',
    'olympics', 'gold medal', 'podium', 'torch', 'opening ceremony',
    'marathon', 'running', 'finish line', 'medal', 'water station',
    'triathlon', 'swimming', 'cycling', 'running', 'transition',
    'gymnastics', 'balance beam', 'vault', 'floor routine', 'rings',
    'figure skating', 'ice rink', 'spin', 'jump', 'pair skating',
    'snowboarding', 'halfpipe', 'slope', 'powder', 'trick',
    'surfing', 'wave', 'board', 'wetsuit', 'barrel', 'pipeline',
    'skateboarding', 'ramp', 'ollie', 'kickflip', 'grind',
    'rock concert', 'stage', 'crowd', 'guitar solo', 'encore',
    'orchestra', 'conductor', 'violin', 'cello', 'piano', 'drum',
    'ballet', 'tutu', 'pointe', 'pirouette', 'plie', 'leap',
    'broadway', 'musical', 'curtain call', 'standing ovation',
    'art museum', 'painting', 'sculpture', 'gallery', 'frame',
    'street art', 'graffiti', 'mural', 'spray paint', 'stencil',
    'pottery', 'clay', 'wheel', 'kiln', 'glaze', 'vase',
    'photography', 'camera', 'lens', 'tripod', 'flash', 'portrait',
    'film set', 'director', 'actor', 'camera', 'lights', 'action',
    'magic show', 'rabbit', 'hat', 'cards', 'disappear', 'saw',
    'circus', 'trapeze', 'tightrope', 'juggling', 'clown', 'lion',
    'zoo', 'safari', 'aquarium', 'petting zoo', 'feeding', 'tour',
    'farm', 'tractor', 'barn', 'hay', 'chicken', 'cow', 'pig',
    'ranch', 'horse', 'rodeo', 'lasso', 'cowboy', 'cowgirl',
    'space station', 'astronaut', 'zero gravity', 'spacewalk', 'earth',
    'mars', 'rover', 'rocket', 'launch', 'orbit', 'moon',
    'submarine', 'periscope', 'torpedo', 'sonar', 'depth',
    'pirate ship', 'treasure map', 'parrot', 'anchor', 'sail',
    'castle', 'drawbridge', 'moat', 'dungeon', 'throne', 'knight',
    'fairy tale', 'princess', 'dragon', 'knight', 'castle', 'magic',
    'superhero', 'cape', 'mask', 'villain', 'rescue', 'powers',
    'detective', 'magnifying glass', 'clue', 'mystery', 'suspect',
    'time machine', 'past', 'future', 'clock', 'invention',
    'invention', 'light bulb', 'idea', 'blueprint', 'experiment',
    'laboratory', 'beaker', 'formula', 'discovery', 'scientist',
    'library', 'ancient', 'scroll', 'book', 'ladder', 'quiet',
    'treehouse', 'ladder', 'rope', 'hideout', 'secret', 'club',
    'lemonade stand', 'pitcher', 'cup', 'sign', 'money', 'customer',
    'garage sale', 'table', 'price tag', 'bargain', 'shopping',
    'moving', 'boxes', 'truck', 'furniture', 'unpacking',
    'house cleaning', 'vacuum', 'mop', 'dust', 'organize',
    'cooking show', 'chef', 'ingredients', 'recipe', 'tasting',
    'game show', 'buzzer', 'prize', 'contestant', 'host',
    'talk show', 'sofa', 'interview', 'audience', 'applause',
    'news anchor', 'desk', 'camera', 'teleprompter', 'breaking news',
    'weather report', 'map', 'forecast', 'temperature', 'radar',
    'sports game', 'stadium', 'crowd', 'scoreboard', 'referee',
    'concert', 'band', 'stage', 'lights', 'crowd', 'encore',
    'wedding', 'ceremony', 'reception', 'dance', 'cake',
    'baby shower', 'gifts', 'games', 'cake', 'decorations',
    'retirement party', 'speech', 'cake', 'gifts', 'celebration',
    'family reunion', 'picnic', 'photos', 'stories', 'hugs',
    'slumber party', 'pillow fight', 'movies', 'popcorn', 'gossip',
    'pool party', 'swimming', 'float', 'grill', 'music',
    'backyard', 'grill', 'lawn', 'garden', 'patio', 'fence',
    'road trip', 'car', 'map', 'snacks', 'music', 'highway',
    'camping', 'tent', 'fire', 'stars', 'marshmallows', 'stories',
    'beach day', 'umbrella', 'sunscreen', 'towels', 'volleyball',
    'hiking trail', 'boots', 'backpack', 'water', 'trail', 'view',
    'fishing trip', 'boat', 'rod', 'bait', 'cooler', 'catch',
    'ski trip', 'lodge', 'slopes', 'hot chocolate', 'fireplace',
    'cruise ship', 'deck', 'pool', 'buffet', 'island', 'excursion',
    'safari', 'jeep', 'binoculars', 'animals', 'sunset', 'wildlife',
    'museum', 'exhibit', 'tour', 'painting', 'sculpture', 'gift shop',
    'amusement park', 'rides', 'cotton candy', 'roller coaster', 'ferris wheel',
    'water park', 'slide', 'wave pool', 'lazy river', 'splash',
    'bowling', 'lane', 'ball', 'pins', 'shoes', 'strike',
    'mini golf', 'putter', 'windmill', 'obstacle', 'hole',
    'arcade', 'games', 'tokens', 'prizes', 'joystick', 'screen',
    'escape room', 'puzzle', 'clue', 'lock', 'timer', 'mystery',
    'karaoke', 'microphone', 'screen', 'song', 'stage', 'crowd',
    'trivia night', 'team', 'questions', 'score', 'prize',
    'potluck', 'dish', 'table', 'variety', 'sharing', 'recipe',
    'brunch', 'mimosa', 'eggs', 'pancakes', 'buffet', 'weekend',
    'happy hour', 'drinks', 'appetizers', 'special', 'social',
    'book club', 'discussion', 'wine', 'snacks', 'opinion',
    'yoga class', 'mat', 'stretch', 'breathe', 'pose', 'relax',
    'gym', 'weights', 'treadmill', 'workout', 'sweat', 'muscle',
    'spa day', 'massage', 'facial', 'manicure', 'pedicure', 'relax',
    'hair salon', 'cut', 'color', 'style', 'mirror', 'chair',
    'tailor', 'measure', 'sew', 'fit', 'fabric', 'alteration',
    'flower shop', 'bouquet', 'vase', 'arrangement', 'delivery',
    'bakery', 'bread', 'pastry', 'cake', 'smell', 'fresh',
    'butcher', 'meat', 'cut', 'scale', 'wrap', 'counter',
    'fish market', 'seafood', 'ice', 'scale', 'fresh', 'catch',
    'farmers market', 'produce', 'stand', 'organic', 'local', 'fresh',
    'food truck', 'window', 'order', 'street', 'variety', 'quick',
    'coffee shop', 'latte', 'espresso', 'pastry', 'wifi', 'cozy',
    'ice cream shop', 'cone', 'scoop', 'topping', 'sundae', 'sweet',
    'pizza place', 'slice', 'oven', 'topping', 'cheese', 'crust',
    'sushi restaurant', 'roll', 'sashimi', 'chopsticks', 'soy sauce',
    'taco stand', 'tortilla', 'salsa', 'guacamole', 'lime', 'spicy',
    'buffet', 'plate', 'variety', 'seconds', 'dessert', 'full',
    'brunch', 'eggs benedict', 'mimosa', 'avocado', 'toast', 'weekend',
  ],
};
